apiVersion: v1
kind: Service
metadata:
  labels:
    cherry-syte.service: app
  name: app
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    cherry-syte.service: app
status:
  loadBalancer: {}
