apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cherry-syte
    spec:
      containers:
      - image: j00mz/cherry-syte:latest
        name: cherry-syte
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
